### ISSUE TITLE
Can't compile "error: conflicting declaration ‘typedef uint32_t uint32’"

### ISSUE THREAD

**Issue by catsuperberg** [Crow-bar/xash3d-fwgs#1]
Can't compile project per instructions. When starting a build i get a bunch of errors pointing to:

```
../mainui/miniutl/miniutl.h:185:18: error: conflicting declaration ‘typedef uint32_t uint32’
  185 | typedef uint32_t uint32;
```

Build failed message is:
```
Build failed
 -> task in 'menu' failed with exit status 1 (run with -v to display more information)
```

I tried to build it on both raspberry pi running manjaro and on WSL2 running ubuntu (can successfully build x86 xash3D from FWGS/xash3d-fwgs). I tried cloning and building whole pspdev, than just psptoolchain+pspdev. Tried older commits, tried commit from tagged release ("Xash3D PSP v0.20 build 2603"). No difference i still get those conflicting declarations.

**Comment by Crow-bar** [comment]
> Can't compile project per instructions. When starting a build i get a bunch of errors pointing to:
> 
> ```
> ../mainui/miniutl/miniutl.h:185:18: error: conflicting declaration ‘typedef uint32_t uint32’
>   185 | typedef uint32_t uint32;
> ```
> 
> Build failed message is:
> 
> ```
> Build failed
>  -> task in 'menu' failed with exit status 1 (run with -v to display more information)
> ```
> 
> I tried to build it on both raspberry pi running manjaro and on WSL2 running ubuntu (can successfully build x86 xash3D from FWGS/xash3d-fwgs). I tried cloning and building whole pspdev, than just psptoolchain+pspdev. Tried older commits, tried commit from tagged release ("Xash3D PSP v0.20 build 2603"). No difference i still get those conflicting declarations.

The problem occurs when compiling with a new pspsdk. I'll fix it later.

At the moment i can offer my distribution pspsdk compiled under ubuntu

**Comment by catsuperberg** [comment]
> The problem occurs when compiling with a new pspsdk. I'll fix it later.
> 
> At the moment i can offer my distribution pspsdk compiled under ubuntu

I'm ok. Just wanted to try the latest version))
Thought to mention that build doesn't work right now.

**Comment by Crow-bar** [comment]
> I'm ok. Just wanted to try the latest version))
> Thought to mention that build doesn't work right now.

Ok thanks, new version coming soon
