### ISSUE TITLE
Xash3D won't connect to LAN server

### ISSUE THREAD

**Issue by marshallovski** [Crow-bar/xash3d-fwgs#3]
See the attached photo:

![IMG_20230917_205547](https://github.com/Crow-bar/xash3d-fwgs/assets/68496774/51c22f7f-be21-4451-859d-460d97ffeef2)

Wi-Fi switch is turned on (means the Wi-Fi is enabled). There's no multiplayer on PSP Xash3D version, or I need somehow manually connect to Wi-Fi?

**Comment by Crow-bar** [comment]
Network play is not implemented.

It may be implemented in the future, but many other problems need to be solved first
