### ISSUE TITLE
Blueshift Doesn't Work On PSP 3000

### ISSUE THREAD

**Issue by EmeraldTuxedo56** [Crow-bar/xash3d-fwgs#4]
When I Copy My Blueshift Files And Then Switch Games It Says There Isn't Enough Memory And The PSP Returns To The XMB

**Comment by Crow-bar** [comment]
Game change menu doesn't work. You need to create a START.CMD file with the commands `-game bshift +sv_validate_changelevel 0`

START.CMD should be in the Xash3d folder.

**Comment by tylerhdang** [comment]
> Game change menu doesn't work. You need to create a START.CMD file with the commands `-game bshift +sv_validate_changelevel 0`
> 
> START.CMD should be in the Xash3d folder.

Hello, thank you for your response, this seem to get Blue-Shift to work properly instead of crashing or showing a Xash Error, however now I can't change my game back to Half-Life. Is there a command to fix this as well?

**Comment by Crow-bar** [comment]
> > Game change menu doesn't work. You need to create a START.CMD file with the commands `-game bshift +sv_validate_changelevel 0`
> > START.CMD should be in the Xash3d folder.
> 
> Hello, thank you for your response, this seem to get Blue-Shift to work properly instead of crashing or showing a Xash Error, however now I can't change my game back to Half-Life. Is there a command to fix this as well?

Remove `-game bshift` from start.cmd)
